import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { StickyNavbar } from '@/components/StickyNavbar'
import { Providers } from './GlobalRedux/provider';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <Providers>
        <StickyNavbar/>
         {children}
         </Providers>
        </body>
    </html>
  )
}
